version: '3'
services:
  warp:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      BABEL_ENV: development
    volumes:
      - ../:/app
      - /app/node_modules/
  
  
